name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Backend Tests and Build
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Adjust to the version you are using

      - name: Install dependencies for backend
        run: |
          cd backend
          npm install

      - name: Run backend tests
        run: |
          cd backend
          npm test

      - name: Build backend
        run: |
          cd backend
          npm run build

      - name: Deploy Backend
        run: |
          # Add commands to deploy the backend (e.g., using Docker or a cloud service)

  # Job 2: Frontend Tests and Build
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Adjust to the version you are using

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm test

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Deploy Frontend (Optional)
        run: |
          # Add commands to deploy the frontend

  # Job 3: Deployment (Optional)
  deploy:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Backend and Frontend
        run: |
          # Add deployment steps for both backend and frontend, 
          # e.g., deploy to a cloud platform, run Docker commands, etc.
